name: Update Medhome Feed

on:
  schedule:
    - cron: '0 3 * * *' # Каждый день в 5 утра по Киеву
  workflow_dispatch: # Чтобы можно было запустить вручную

permissions:
  contents: write

jobs:
  run-parser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml

      - name: Run script
        run: |
          mkdir -p public
          python medhome.py --output public/medhome_reviews_feed.xml

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public/medhome_reviews_feed.xml
          git commit -m "Auto-update feed" || exit 0
          git push
